
const Products = {
  dress1: require('./products/dress1.jpg'),
  dress2: require('./products/dress2.jpg'),
  dress3: require('./products/dress3.jpg'),
  dress4: require('./products/dress4.jpg'),
  dress5: require('./products/dress5.jpg'),
  dress6: require('./products/dress6.jpg'),
  dress7: require('./products/dress7.jpg'),
  dress8: require('./products/dress8.jpg'),
  dress9: require('./products/dress9.jpg'),
  dress10: require('./products/dress10.jpg'),

  tshirt1: require('./products/tshirt1.jpg'),
  tshirt2: require('./products/tshirt2.jpg'),
  tshirt3: require('./products/tshirt3.jpg'),
  tshirt4: require('./products/tshirt4.jpg'),
  tshirt5: require('./products/tshirt5.jpg'),
  tshirt6: require('./products/tshirt6.jpg'),
  tshirt7: require('./products/tshirt7.jpg'),
  tshirt8: require('./products/tshirt8.jpg'),
  tshirt9: require('./products/tshirt9.jpg'),
  tshirt10: require('./products/tshirt10.jpg'),

  shoes1: require('./products/shoe1.jpg'),
  shoes2: require('./products/shoe2.jpg'),
  shoes3: require('./products/shoe3.jpg'),
  shoes4: require('./products/shoe4.jpg'),
  shoes5: require('./products/shoe5.jpg'),
  shoes6: require('./products/shoe6.jpg'),
  shoes7: require('./products/shoe7.jpg'),
  shoes8: require('./products/shoe8.jpg'),
  shoes9: require('./products/shoe9.jpg'),
  shoes10: require('./products/shoe10.jpg'),

  jacket1: require('./products/jacket1.jpg'),
  jacket2: require('./products/jacket2.jpg'),
  jacket3: require('./products/jacket3.jpg'),
  jacket4: require('./products/jacket4.jpg'),
  jacket5: require('./products/jacket5.jpg'),
  jacket6: require('./products/jacket6.jpg'),
  jacket7: require('./products/jacket7.jpg'),
  jacket8: require('./products/jacket8.jpg'),
  jacket9: require('./products/jacket9.jpg'),
  jacket10: require('./products/jacket10.jpg'),

  bag1: require('./products/bag1.jpg'),
  bag2: require('./products/bag2.jpg'),
  bag3: require('./products/bag3.jpg'),
  bag4: require('./products/bag4.jpg'),
  bag5: require('./products/bag5.jpg'),
  bag6: require('./products/bag6.jpg'),
  bag7: require('./products/bag7.jpg'),
  bag8: require('./products/bag8.jpg'),
  bag9: require('./products/bag9.jpg'),
  bag10: require('./products/bag10.jpg'),
};

export default Products;
